### PR TITLE
Use esling-plugin-import

### PR DESCRIPTION
**Pull request by manosim**
> This plugin intends to support linting of ES2015+ (ES6+) import/export syntax, and prevent issues with misspelling of file paths and import names.

More information: https://www.npmjs.com/package/eslint-plugin-import

### CODE REVIEW

**Comment by JakeSidSmith** [comment]
Think you need to define rules for this, otherwise it'll do nothing:

From their docs:

```yml
rules:
  import/no-unresolved: [2, {commonjs: true, amd: true}]
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
```

**Comment by JakeSidSmith** [comment]
@will-ockmore also made a good point. Unsure if this will work with our custom `'^/import'`s

**Comment by pmg103** [comment]
But... imagine the win!

**Comment by isidornygren** [comment]
Superceded by https://github.com/dabapps/eslint-config-dabapps/pull/43

**Pull request closed without merging**
